package org.admany.lc2h.data.cache;

import mcjty.lostcities.api.LostChunkCharacteristics;
import mcjty.lostcities.varia.ChunkCoord;
import mcjty.lostcities.worldgen.lost.BuildingInfo;

import java.util.Map;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ConcurrentMap;

/**
 * Per-provider mutable cache state for the BuildingInfo replacement.
 *
 * <p>It deliberately lives outside a mixin package. Mixin-generated bytecode
 * may reference this type from transformed Lost Cities classes, while Mixin
 * rejects direct references to helper classes owned by a mixin package.</p>
 */
public final class BuildingInfoCacheScope {
    public final ConcurrentMap<ChunkCoord, LostChunkCharacteristics> cityInfo = new ConcurrentHashMap<>();
    /**
     * Results produced by Lost Cities' own characteristics resolver. This is
     * deliberately separate from {@link #cityInfo}: the latter belongs to
     * LC2H's optional replacement implementation while this map only ever
     * stores an already-completed native result.
     */
    public final ConcurrentMap<ChunkCoord, LostChunkCharacteristics> nativeCharacteristics = new ConcurrentHashMap<>();
    public final ConcurrentMap<ChunkCoord, CompletableFuture<LostChunkCharacteristics>> nativeCharacteristicFlights = new ConcurrentHashMap<>();
    /** One producer builds a cold LC2H characteristic value per coordinate. */
    public final ConcurrentMap<ChunkCoord, CompletableFuture<LostChunkCharacteristics>> characteristicFlights = new ConcurrentHashMap<>();
    public final ConcurrentMap<ChunkCoord, BuildingInfo> buildingInfo = new ConcurrentHashMap<>();
    public final ConcurrentMap<ChunkCoord, Integer> cityLevel = new ConcurrentHashMap<>();
    public final ConcurrentMap<ChunkCoord, Boolean> cityRaw = new ConcurrentHashMap<>();
    public final ConcurrentMap<ChunkCoord, Boolean> highway = new ConcurrentHashMap<>();
    public final ConcurrentMap<ChunkCoord, Long> multiHeightStats = new ConcurrentHashMap<>();
    public final ConcurrentMap<Map.Entry<ChunkCoord, ChunkCoord>, Boolean> multiBoundary = new ConcurrentHashMap<>();
    public final ConcurrentMap<ChunkCoord, Object> buildingLocks = new ConcurrentHashMap<>();

    public void clear() {
        cityInfo.clear();
        nativeCharacteristics.clear();
        nativeCharacteristicFlights.clear();
        characteristicFlights.clear();
        buildingInfo.clear();
        cityLevel.clear();
        cityRaw.clear();
        highway.clear();
        multiHeightStats.clear();
        multiBoundary.clear();
        buildingLocks.clear();
    }
}
