package org.admany.lc2h.data.cache;

import mcjty.lostcities.api.LostChunkCharacteristics;
import mcjty.lostcities.varia.ChunkCoord;
import mcjty.lostcities.worldgen.lost.BuildingInfo;

import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ConcurrentMap;

/**
 * Per-provider mutable cache state for the BuildingInfo replacement.
 *
 * <p>It deliberately lives outside a mixin package. Mixin-generated bytecode
 * may reference this type from transformed Lost Cities classes, while Mixin
 * rejects direct references to helper classes owned by a mixin package.</p>
 */
public final class BuildingInfoCacheScope {
    public final ConcurrentMap<ChunkCoord, LostChunkCharacteristics> cityInfo = new ConcurrentHashMap<>();
    public final ConcurrentMap<ChunkCoord, BuildingInfo> buildingInfo = new ConcurrentHashMap<>();
    public final ConcurrentMap<ChunkCoord, Integer> cityLevel = new ConcurrentHashMap<>();
    public final ConcurrentMap<ChunkCoord, Boolean> cityRaw = new ConcurrentHashMap<>();
    public final ConcurrentMap<ChunkCoord, Boolean> highway = new ConcurrentHashMap<>();
    public final ConcurrentMap<ChunkCoord, Long> multiHeightStats = new ConcurrentHashMap<>();
    public final ConcurrentMap<Map.Entry<ChunkCoord, ChunkCoord>, Boolean> multiBoundary = new ConcurrentHashMap<>();
    public final ConcurrentMap<ChunkCoord, Object> buildingLocks = new ConcurrentHashMap<>();

    public void clear() {
        cityInfo.clear();
        buildingInfo.clear();
        cityLevel.clear();
        cityRaw.clear();
        highway.clear();
        multiHeightStats.clear();
        multiBoundary.clear();
        buildingLocks.clear();
    }
}
